"""Seed the shared scenario library into Supabase.

These scenarios follow the exact contract from
`life_decision_model/schemas.py` (SCENARIO_EXAMPLE /
REQUIRED_SCENARIO_FIELDS_FOR_SCORING), so they can be scored by
`life_decision_model.run_model()` as soon as they're loaded.

They're stored with user_email = db.GLOBAL_USER_EMAIL, which means every
user sees them (see db.list_model_scenarios_data).

Run once (or whenever you want to refresh the library):

    python seed_scenarios.py
"""

from __future__ import annotations

import db

SCENARIOS: list[dict] = [
    {
        "scenario_id": "second_job",
        "name": "Take a part-time second job",
        "category": "money",
        "goal_tags": ["money", "career"],
        "best_for_requests": ["increase_income", "save_money"],
        "time_required_per_week": 12,
        "budget_required": "low",
        "skill_required": 2,
        "intensity": 4,
        "preferred_formats": ["clear_structure", "routine"],
        "structure_level": 4,
        "social_intensity": 3,
        "feedback_level": 2,
        "impact": {
            "career": 1, "money": 5, "learning": 0,
            "relationships": -3, "health": -2, "hobby": -4, "energy": -4,
        },
        "reversibility": 4,
        "uncertainty_level": 2,
        "risk_tags": ["overload", "less_time_for_relationships"],
        "not_recommended_if": ["low_energy_and_low_free_time", "burnout"],
        "main_benefit": "Fastest way to increase income",
        "main_cost": "High cost to energy, relationships, and free time",
        "tradeoffs": [
            "Improves money quickly",
            "Can increase overload",
            "Reduces free time and relationship time",
        ],
        "first_step": "Map out your weekly schedule and confirm whether 12 extra hours are realistic.",
    },
    {
        "scenario_id": "salary_negotiation",
        "name": "Negotiate a raise",
        "category": "career",
        "goal_tags": ["money", "career"],
        "best_for_requests": ["increase_income", "build_confidence"],
        "time_required_per_week": 2,
        "budget_required": "low",
        "skill_required": 3,
        "intensity": 3,
        "preferred_formats": ["clear_structure"],
        "structure_level": 4,
        "social_intensity": 4,
        "feedback_level": 5,
        "impact": {
            "career": 3, "money": 4, "learning": 1,
            "relationships": 0, "health": 0, "hobby": 0, "energy": -1,
        },
        "reversibility": 5,
        "uncertainty_level": 3,
        "risk_tags": ["short_term_stress"],
        "not_recommended_if": ["fear_of_failure"],
        "main_benefit": "Increases income without adding extra working hours",
        "main_cost": "Requires a difficult, high-stakes conversation",
        "tradeoffs": [
            "Low time cost",
            "Emotionally demanding",
            "Outcome isn't guaranteed",
        ],
        "first_step": "Write down your concrete achievements from the last 6-12 months.",
    },
    {
        "scenario_id": "start_side_business",
        "name": "Start a side business",
        "category": "money",
        "goal_tags": ["money", "career"],
        "best_for_requests": ["start_business", "increase_income"],
        "time_required_per_week": 15,
        "budget_required": "medium",
        "skill_required": 3,
        "intensity": 4,
        "preferred_formats": ["flexible", "creative"],
        "structure_level": 2,
        "social_intensity": 3,
        "feedback_level": 2,
        "impact": {
            "career": 2, "money": 3, "learning": 3,
            "relationships": -2, "health": -2, "hobby": -3, "energy": -4,
        },
        "reversibility": 3,
        "uncertainty_level": 4,
        "risk_tags": ["financial_risk", "overload"],
        "not_recommended_if": ["financial_risk", "low_energy_and_low_free_time"],
        "main_benefit": "Long-term income potential and independence",
        "main_cost": "High uncertainty and significant time investment",
        "tradeoffs": [
            "High upside if it works",
            "No guaranteed return",
            "Demands consistent weekly effort",
        ],
        "first_step": "Validate the idea with 5 potential customers before building anything.",
    },
    {
        "scenario_id": "switch_career",
        "name": "Switch to a new career field",
        "category": "career",
        "goal_tags": ["career", "learning"],
        "best_for_requests": ["change_career", "find_new_job"],
        "time_required_per_week": 10,
        "budget_required": "medium",
        "skill_required": 2,
        "intensity": 4,
        "preferred_formats": ["clear_structure", "flexible"],
        "structure_level": 3,
        "social_intensity": 3,
        "feedback_level": 3,
        "impact": {
            "career": 4, "money": -2, "learning": 4,
            "relationships": -1, "health": -1, "hobby": -2, "energy": -3,
        },
        "reversibility": 2,
        "uncertainty_level": 4,
        "risk_tags": ["financial_risk", "uncertainty"],
        "not_recommended_if": ["financial_risk", "uncertainty"],
        "main_benefit": "Long-term alignment between work and what matters to you",
        "main_cost": "Possible income dip and a steep early learning curve",
        "tradeoffs": [
            "High long-term satisfaction potential",
            "Short-term income risk",
            "Low reversibility once committed",
        ],
        "first_step": "Talk to 3 people already working in the target field.",
    },
    {
        "scenario_id": "build_portfolio",
        "name": "Build a portfolio project",
        "category": "career",
        "goal_tags": ["career", "learning"],
        "best_for_requests": ["find_new_job", "change_career", "learn_new_skill"],
        "time_required_per_week": 8,
        "budget_required": "low",
        "skill_required": 2,
        "intensity": 3,
        "preferred_formats": ["clear_structure", "creative"],
        "structure_level": 3,
        "social_intensity": 1,
        "feedback_level": 2,
        "impact": {
            "career": 3, "money": 0, "learning": 4,
            "relationships": 0, "health": 0, "hobby": -2, "energy": -2,
        },
        "reversibility": 5,
        "uncertainty_level": 2,
        "risk_tags": [],
        "not_recommended_if": ["low_energy_and_low_free_time"],
        "main_benefit": "Tangible proof of skill that strengthens job applications",
        "main_cost": "Steady weekly time investment with no immediate payoff",
        "tradeoffs": [
            "Low risk, fully reversible",
            "Builds visible skill evidence",
            "Slow, no instant results",
        ],
        "first_step": "Pick one specific project and define what 'done' looks like.",
    },
    {
        "scenario_id": "online_course",
        "name": "Take an online course",
        "category": "learning",
        "goal_tags": ["learning", "career"],
        "best_for_requests": ["learn_new_skill", "change_career"],
        "time_required_per_week": 5,
        "budget_required": "low",
        "skill_required": 1,
        "intensity": 2,
        "preferred_formats": ["clear_structure", "routine"],
        "structure_level": 4,
        "social_intensity": 1,
        "feedback_level": 3,
        "impact": {
            "career": 2, "money": 0, "learning": 5,
            "relationships": 0, "health": 0, "hobby": -1, "energy": -1,
        },
        "reversibility": 5,
        "uncertainty_level": 1,
        "risk_tags": [],
        "not_recommended_if": [],
        "main_benefit": "Low-risk, structured way to build a new skill",
        "main_cost": "Requires consistent weekly time over several weeks",
        "tradeoffs": [
            "Very low risk",
            "Clear structure and pacing",
            "Slower than hands-on practice",
        ],
        "first_step": "Pick one course, block 1 hour on your calendar 5x/week.",
    },
    {
        "scenario_id": "get_certification",
        "name": "Get a professional certification",
        "category": "learning",
        "goal_tags": ["learning", "career"],
        "best_for_requests": ["get_certification", "change_career", "find_new_job"],
        "time_required_per_week": 6,
        "budget_required": "medium",
        "skill_required": 2,
        "intensity": 3,
        "preferred_formats": ["clear_structure", "routine"],
        "structure_level": 5,
        "social_intensity": 1,
        "feedback_level": 4,
        "impact": {
            "career": 3, "money": -1, "learning": 4,
            "relationships": 0, "health": 0, "hobby": -2, "energy": -2,
        },
        "reversibility": 5,
        "uncertainty_level": 2,
        "risk_tags": [],
        "not_recommended_if": [],
        "main_benefit": "Recognized credential that signals competence to employers",
        "main_cost": "Exam fees and a fixed study schedule",
        "tradeoffs": [
            "Strong external validation",
            "Costs money and structured time",
            "Mostly low risk",
        ],
        "first_step": "Check the certification's prerequisites and exam date.",
    },
    {
        "scenario_id": "find_mentor",
        "name": "Find a mentor",
        "category": "career",
        "goal_tags": ["career", "learning"],
        "best_for_requests": ["build_confidence", "change_career", "find_new_job"],
        "time_required_per_week": 1,
        "budget_required": "low",
        "skill_required": 1,
        "intensity": 1,
        "preferred_formats": ["social", "flexible"],
        "structure_level": 2,
        "social_intensity": 4,
        "feedback_level": 5,
        "impact": {
            "career": 2, "money": 0, "learning": 3,
            "relationships": 1, "health": 0, "hobby": 0, "energy": 1,
        },
        "reversibility": 5,
        "uncertainty_level": 2,
        "risk_tags": [],
        "not_recommended_if": [],
        "main_benefit": "Outside perspective and faster feedback loops, low time cost",
        "main_cost": "Takes time to find the right person and build trust",
        "tradeoffs": [
            "Very low risk and low time cost",
            "High potential value",
            "Depends on finding the right fit",
        ],
        "first_step": "List 3 people you admire professionally and reach out to one.",
    },
    {
        "scenario_id": "daily_exercise",
        "name": "Start a daily exercise routine",
        "category": "health",
        "goal_tags": ["health", "balance"],
        "best_for_requests": ["improve_health", "reduce_stress", "build_habit"],
        "time_required_per_week": 4,
        "budget_required": "low",
        "skill_required": 1,
        "intensity": 3,
        "preferred_formats": ["routine", "clear_structure"],
        "structure_level": 4,
        "social_intensity": 1,
        "feedback_level": 2,
        "impact": {
            "career": 0, "money": 0, "learning": 0,
            "relationships": 0, "health": 5, "hobby": 1, "energy": 3,
        },
        "reversibility": 5,
        "uncertainty_level": 1,
        "risk_tags": [],
        "not_recommended_if": [],
        "main_benefit": "Improves energy and health with a modest weekly time cost",
        "main_cost": "Requires consistency to see results",
        "tradeoffs": [
            "Low risk, high health upside",
            "Boosts energy for everything else",
            "Needs habit-building discipline",
        ],
        "first_step": "Pick 3 fixed days/times this week and put them on your calendar.",
    },
    {
        "scenario_id": "improve_sleep",
        "name": "Fix your sleep schedule",
        "category": "health",
        "goal_tags": ["health", "balance"],
        "best_for_requests": ["improve_health", "reduce_stress"],
        "time_required_per_week": 2,
        "budget_required": "low",
        "skill_required": 1,
        "intensity": 2,
        "preferred_formats": ["routine"],
        "structure_level": 5,
        "social_intensity": 1,
        "feedback_level": 2,
        "impact": {
            "career": 1, "money": 0, "learning": 0,
            "relationships": 0, "health": 4, "hobby": 0, "energy": 4,
        },
        "reversibility": 5,
        "uncertainty_level": 1,
        "risk_tags": [],
        "not_recommended_if": [],
        "main_benefit": "One of the highest-leverage, lowest-cost changes for energy",
        "main_cost": "Requires discipline around a fixed bedtime",
        "tradeoffs": [
            "Very low cost, very high energy payoff",
            "Effects compound over other goals",
            "Needs consistency to stick",
        ],
        "first_step": "Set a fixed wake-up time and stick to it for 7 days straight.",
    },
    {
        "scenario_id": "therapy",
        "name": "Start therapy or counseling",
        "category": "health",
        "goal_tags": ["health", "balance"],
        "best_for_requests": ["reduce_stress", "build_confidence", "improve_health"],
        "time_required_per_week": 2,
        "budget_required": "medium",
        "skill_required": 1,
        "intensity": 3,
        "preferred_formats": ["social", "flexible"],
        "structure_level": 3,
        "social_intensity": 4,
        "feedback_level": 4,
        "impact": {
            "career": 1, "money": -1, "learning": 1,
            "relationships": 2, "health": 4, "hobby": 0, "energy": 2,
        },
        "reversibility": 5,
        "uncertainty_level": 2,
        "risk_tags": [],
        "not_recommended_if": [],
        "main_benefit": "Professional support for processing stress and patterns",
        "main_cost": "Ongoing cost and emotional effort, especially early on",
        "tradeoffs": [
            "Strong long-term wellbeing payoff",
            "Recurring cost",
            "Can feel uncomfortable at first",
        ],
        "first_step": "Research 3 therapists or platforms that fit your budget.",
    },
    {
        "scenario_id": "weekly_date_night",
        "name": "Schedule weekly quality time with your partner",
        "category": "relationships",
        "goal_tags": ["relationships", "balance"],
        "best_for_requests": ["improve_relationship", "find_balance"],
        "time_required_per_week": 3,
        "budget_required": "low",
        "skill_required": 1,
        "intensity": 1,
        "preferred_formats": ["routine", "social"],
        "structure_level": 3,
        "social_intensity": 5,
        "feedback_level": 3,
        "impact": {
            "career": 0, "money": -1, "learning": 0,
            "relationships": 5, "health": 1, "hobby": 1, "energy": 1,
        },
        "reversibility": 5,
        "uncertainty_level": 1,
        "risk_tags": [],
        "not_recommended_if": [],
        "main_benefit": "Direct, reliable boost to relationship satisfaction",
        "main_cost": "Modest, regular time and small budget commitment",
        "tradeoffs": [
            "Very low risk",
            "High relationship payoff",
            "Needs to become a real habit to count",
        ],
        "first_step": "Pick a recurring day/time this week and put it on both calendars.",
    },
    {
        "scenario_id": "reconnect_friends",
        "name": "Reconnect with friends",
        "category": "relationships",
        "goal_tags": ["relationships", "balance"],
        "best_for_requests": ["build_new_relationships", "improve_relationship", "find_balance"],
        "time_required_per_week": 2,
        "budget_required": "low",
        "skill_required": 1,
        "intensity": 1,
        "preferred_formats": ["social", "flexible"],
        "structure_level": 2,
        "social_intensity": 5,
        "feedback_level": 2,
        "impact": {
            "career": 0, "money": 0, "learning": 0,
            "relationships": 4, "health": 0, "hobby": 2, "energy": 1,
        },
        "reversibility": 5,
        "uncertainty_level": 1,
        "risk_tags": [],
        "not_recommended_if": [],
        "main_benefit": "Low-cost way to rebuild a support network",
        "main_cost": "Requires reaching out first, which can feel awkward",
        "tradeoffs": [
            "Very low risk",
            "Improves both relationships and free time",
            "Slow to build back up",
        ],
        "first_step": "Message one friend you haven't talked to in a while.",
    },
    {
        "scenario_id": "join_community",
        "name": "Join a community or club",
        "category": "relationships",
        "goal_tags": ["relationships", "balance", "learning"],
        "best_for_requests": ["build_new_relationships", "find_balance"],
        "time_required_per_week": 3,
        "budget_required": "low",
        "skill_required": 1,
        "intensity": 2,
        "preferred_formats": ["social", "routine"],
        "structure_level": 3,
        "social_intensity": 5,
        "feedback_level": 2,
        "impact": {
            "career": 0, "money": -1, "learning": 1,
            "relationships": 4, "health": 1, "hobby": 2, "energy": 0,
        },
        "reversibility": 5,
        "uncertainty_level": 2,
        "risk_tags": [],
        "not_recommended_if": [],
        "main_benefit": "New social circle plus a recurring reason to get out",
        "main_cost": "Can feel uncomfortable until you find the right group",
        "tradeoffs": [
            "Low risk",
            "Builds relationships and free-time satisfaction together",
            "Takes a few tries to find the right fit",
        ],
        "first_step": "Find and attend one local meetup or club session this month.",
    },
    {
        "scenario_id": "digital_detox",
        "name": "Weekly digital detox",
        "category": "balance",
        "goal_tags": ["balance", "health"],
        "best_for_requests": ["reduce_stress", "find_balance"],
        "time_required_per_week": 3,
        "budget_required": "low",
        "skill_required": 1,
        "intensity": 2,
        "preferred_formats": ["routine"],
        "structure_level": 4,
        "social_intensity": 1,
        "feedback_level": 1,
        "impact": {
            "career": 0, "money": 0, "learning": 0,
            "relationships": 1, "health": 2, "hobby": 3, "energy": 2,
        },
        "reversibility": 5,
        "uncertainty_level": 1,
        "risk_tags": [],
        "not_recommended_if": [],
        "main_benefit": "Quick, low-cost reset for stress and free time",
        "main_cost": "Requires sticking to the boundary once set",
        "tradeoffs": [
            "Very low risk",
            "Fast to start",
            "Easy to slip back into old habits",
        ],
        "first_step": "Pick one fixed block this week (e.g. Sunday morning) to go offline.",
    },
    {
        "scenario_id": "set_boundaries",
        "name": "Set boundaries / say no more often",
        "category": "balance",
        "goal_tags": ["balance", "career", "relationships"],
        "best_for_requests": ["reduce_stress", "find_balance", "build_confidence"],
        "time_required_per_week": 1,
        "budget_required": "low",
        "skill_required": 2,
        "intensity": 2,
        "preferred_formats": ["flexible", "social"],
        "structure_level": 2,
        "social_intensity": 3,
        "feedback_level": 2,
        "impact": {
            "career": 0, "money": 0, "learning": 1,
            "relationships": -1, "health": 1, "hobby": 2, "energy": 3,
        },
        "reversibility": 4,
        "uncertainty_level": 2,
        "risk_tags": ["social_pressure"],
        "not_recommended_if": ["social_pressure"],
        "main_benefit": "Frees up time and energy with almost no cost",
        "main_cost": "Can create short-term friction with others",
        "tradeoffs": [
            "Very low time cost",
            "May cause temporary social tension",
            "High payoff for energy and free time",
        ],
        "first_step": "Identify one recurring commitment you can decline this week.",
    },
    {
        "scenario_id": "savings_plan",
        "name": "Build an automatic savings plan",
        "category": "money",
        "goal_tags": ["money", "balance"],
        "best_for_requests": ["save_money", "reduce_stress"],
        "time_required_per_week": 1,
        "budget_required": "low",
        "skill_required": 1,
        "intensity": 1,
        "preferred_formats": ["clear_structure", "routine"],
        "structure_level": 5,
        "social_intensity": 1,
        "feedback_level": 1,
        "impact": {
            "career": 0, "money": 4, "learning": 1,
            "relationships": 0, "health": 0, "hobby": -1, "energy": 0,
        },
        "reversibility": 5,
        "uncertainty_level": 1,
        "risk_tags": [],
        "not_recommended_if": [],
        "main_benefit": "Builds financial security with almost no ongoing effort",
        "main_cost": "Slightly reduces discretionary spending",
        "tradeoffs": [
            "Extremely low risk and time cost",
            "Slow but steady payoff",
            "Easy to set and forget",
        ],
        "first_step": "Set up an automatic transfer to a savings account this week.",
    },
]


def seed() -> None:
    client = db.get_client()
    inserted, updated = 0, 0
    for scenario in SCENARIOS:
        payload = {
            "user_email": db.GLOBAL_USER_EMAIL,
            "title": scenario["name"],
            "data": scenario,
        }
        existing = (
            client.table("scenarios")
            .select("id")
            .eq("user_email", db.GLOBAL_USER_EMAIL)
            .eq("title", scenario["name"])
            .limit(1)
            .execute()
        )
        if existing.data:
            client.table("scenarios").update(payload).eq(
                "id", existing.data[0]["id"]).execute()
            updated += 1
        else:
            client.table("scenarios").insert(payload).execute()
            inserted += 1

    print(f"Done. Inserted {inserted}, updated {updated}, total {len(SCENARIOS)} scenarios.")


if __name__ == "__main__":
    seed()
